/**
 * Migration: Rename tabel "peminjaman" → "permintaan" (lanjutan)
 *
 * Tabel sudah di-rename pada langkah sebelumnya.
 * Script ini melanjutkan rename constraint, index, dan sequence.
 *
 * Jalankan: node scripts/migrate-rename.mjs
 */

import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { neon } from "@neondatabase/serverless";

// ---- muat .env.local secara manual ----
function loadEnvLocal() {
  const file = resolve(process.cwd(), ".env.local");
  if (!existsSync(file)) return;
  const content = readFileSync(file, "utf8");
  for (const line of content.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}

loadEnvLocal();

const url = process.env.DATABASE_URL;
if (!url) {
  console.error("[GAGAL] DATABASE_URL tidak ditemukan.");
  process.exit(1);
}

const sql = neon(url);

async function main() {
  console.log(">>> PINJAM/ATK — Migrasi: peminjaman → permintaan");

  // 1. Cek status tabel
  const [oldExists] = await sql`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'peminjaman'
    ) AS e
  `;
  const [newExists] = await sql`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'permintaan'
    ) AS e
  `;

  if (oldExists.e && !newExists.e) {
    // Tabel masih bernama peminjaman — rename dulu
    console.log("    [1/4] Rename tabel peminjaman → permintaan...");
    await sql`ALTER TABLE peminjaman RENAME TO permintaan`;
    console.log("          ✓ Tabel berhasil di-rename.");
  } else if (newExists.e) {
    console.log("    [1/4] Tabel 'permintaan' sudah ada. Skip rename tabel.");
  } else {
    console.error("    [GAGAL] Tabel 'peminjaman' maupun 'permintaan' tidak ditemukan!");
    process.exit(1);
  }

  // 2. Rename semua constraint yang mengandung "peminjaman" via DO block
  console.log("    [2/4] Rename constraint...");
  await sql`
    DO $$
    DECLARE
      r RECORD;
    BEGIN
      FOR r IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'permintaan'::regclass
        AND conname LIKE '%peminjaman%'
      LOOP
        EXECUTE format(
          'ALTER TABLE permintaan RENAME CONSTRAINT %I TO %I',
          r.conname,
          replace(r.conname, 'peminjaman', 'permintaan')
        );
        RAISE NOTICE 'Constraint: % → %', r.conname, replace(r.conname, 'peminjaman', 'permintaan');
      END LOOP;
    END $$
  `;
  console.log("          ✓ Constraint selesai.");

  // 3. Rename semua index yang mengandung "peminjaman"
  console.log("    [3/4] Rename index...");
  await sql`
    DO $$
    DECLARE
      r RECORD;
    BEGIN
      FOR r IN
        SELECT indexname
        FROM pg_indexes
        WHERE tablename = 'permintaan'
        AND indexname LIKE '%peminjaman%'
      LOOP
        EXECUTE format(
          'ALTER INDEX %I RENAME TO %I',
          r.indexname,
          replace(r.indexname, 'peminjaman', 'permintaan')
        );
        RAISE NOTICE 'Index: % → %', r.indexname, replace(r.indexname, 'peminjaman', 'permintaan');
      END LOOP;
    END $$
  `;
  console.log("          ✓ Index selesai.");

  // 4. Rename sequence (auto-generated by SERIAL)
  console.log("    [4/4] Rename sequence...");
  await sql`
    DO $$
    DECLARE
      r RECORD;
    BEGIN
      FOR r IN
        SELECT sequencename
        FROM pg_sequences
        WHERE schemaname = 'public'
        AND sequencename LIKE '%peminjaman%'
      LOOP
        EXECUTE format(
          'ALTER SEQUENCE %I RENAME TO %I',
          r.sequencename,
          replace(r.sequencename, 'peminjaman', 'permintaan')
        );
        RAISE NOTICE 'Sequence: % → %', r.sequencename, replace(r.sequencename, 'peminjaman', 'permintaan');
      END LOOP;
    END $$
  `;
  console.log("          ✓ Sequence selesai.");

  // 5. Verifikasi
  console.log("\n    --- Verifikasi ---");
  
  const [verify] = await sql`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'permintaan'
    ) AS ok
  `;

  const columns = await sql`
    SELECT column_name 
    FROM information_schema.columns 
    WHERE table_name = 'permintaan' 
    ORDER BY ordinal_position
  `;

  const remaining = await sql`
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'permintaan'::regclass AND conname LIKE '%peminjaman%'
    UNION ALL
    SELECT indexname FROM pg_indexes
    WHERE tablename = 'permintaan' AND indexname LIKE '%peminjaman%'
  `;

  const oldTable = await sql`
    SELECT EXISTS (
      SELECT 1 FROM information_schema.tables 
      WHERE table_schema = 'public' AND table_name = 'peminjaman'
    ) AS e
  `;

  if (verify.ok) {
    console.log("    ✓ Tabel 'permintaan' ada.");
    console.log(`    ✓ Kolom: ${columns.map(c => c.column_name).join(", ")}`);
  } else {
    console.error("    ✗ Tabel 'permintaan' tidak ditemukan!");
  }

  if (!oldTable[0].e) {
    console.log("    ✓ Tabel 'peminjaman' sudah tidak ada.");
  } else {
    console.error("    ✗ Tabel 'peminjaman' masih ada!");
  }

  if (remaining.length === 0) {
    console.log("    ✓ Tidak ada constraint/index yang masih menggunakan nama 'peminjaman'.");
  } else {
    console.error(`    ✗ Masih ada ${remaining.length} objek bernama 'peminjaman':`, remaining);
  }

  console.log("\n>>> Migrasi selesai!");
}

main().catch((e) => {
  console.error("[GAGAL] Migrasi error:", e.message ?? e);
  process.exit(1);
});
